### ISSUE TITLE
Inbound bucket prefix incorrectly applied for automatic trigger in AppFlow stack

### ISSUE THREAD

**Issue by thyagram-aws** [aws-solutions/data-connectors-for-aws-clean-rooms#11]
**Describe the bug**
Inbound bucket prefix is incorrectly applied for automatic trigger in AppFlow stack. It currently reads "inbound/" while appflow stacks have a prefix of "<stackname>-flow"

**To Reproduce**
Install Appflow stack with AutoTrigger ON.
Running the flow drops file into the inbound bucket, but does not trigger Databrew job

**Expected behavior**
Running the flow with AutoTrigger ON should kick start the flow

**Please complete the following information about the solution:**
- Version [ 1.1.0] 

- [ x] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by JimTharioAmazon** [comment]
Included in release v1.0.1.
