### ISSUE TITLE
Assert in unit test that expiry time (ttl) is calculated correctly

### ISSUE THREAD

**Issue by tbelmega** [aws-solutions/data-connectors-for-aws-clean-rooms#36]
**Describe the feature you'd like**
The TTL calculation in brew_run_job/lambda_function.py(https://github.com/aws-solutions/data-connectors-for-aws-clean-rooms/blob/b29eb34cbae86290c81d14acfd20ea51337c7855/source/aws_lambda/brew_run_job/lambda_function.py#L37) is complex enough that it's worth checking with a unit test. Especially since a potential bug in this calculation will likely not be found by manual functional testing, e.g. if the time to live is off by a factor of 60 or so, we probably wouldn't notice for a long time.

The unit test 
test_brew_run_job_lambda_function.py(https://github.com/aws-solutions/data-connectors-for-aws-clean-rooms/blob/b29eb34cbae86290c81d14acfd20ea51337c7855/source/tests/aws_lambda/brew_run_job/test_brew_run_job_lambda_function.py#L93) is executing this line of code, but it's not checking if the result is correct. Let's add an assertion to the test to check if the TTL calculation is what we expect.

**Comment by thyagram-aws** [comment]
Fixed in release v1.2.0
