### ISSUE TITLE
S3 Compression

### ISSUE THREAD

**Issue by tomgilman** [aws-solutions/data-connectors-for-aws-clean-rooms#5]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature you'd like**
We want to support what RedShift Spectrum supports. (usually Snappy). 
https://docs.aws.amazon.com/redshift/latest/dg/c-spectrum-data-files.html

**Additional context**

**Comment by thyagram-aws** [comment]
Compressed files in S3 are supported. File formats and supported compression algorithms are shown in the following table.
https://docs.aws.amazon.com/databrew/latest/dg/supported-data-file-sources.html
